Repository AY2324S1-CS2103T-T15-1/tp, pull requests merged in 2023-11, with the labels that each got.

#132 Fix too many prefix for viewtasks bug
  src/main/java/seedu/address/logic/commands/ViewTasksCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ViewTasksCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewTasksCommandParserTest.java
Labels: type.Bug, severity.Medium

#128 Branch documentation update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/UpdateTaskProgressSequenceDiagram.puml
  docs/diagrams/ViewTasksSequenceDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/CommandParserSequenceDiagram.png
  docs/images/CommandsParserSequenceDiagram.png
  docs/images/CommentClass UML.png
  docs/images/CommentClass.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/GradeClass UML.png
  docs/images/GradeClass.png
  docs/images/GradedTest UML.png
  docs/images/GradedTest.png
  docs/images/UpdateTaskProgressSequenceDiagram.png
  docs/images/ViewTasksSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/UpdateTaskProgressCommand.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#134 Fix message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.Medium

#142 Fix return message bug
  src/main/java/seedu/address/logic/commands/EditGradedTestCommand.java
  src/test/java/seedu/address/logic/commands/EditGradedTestCommandTest.java
Labels: type.Bug, priority.High, severity.High

#148 UI: Enhance UI
  src/main/java/seedu/address/logic/commands/ViewAllAssignmentsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewAllAssignmentsCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/ViewAllAssignmentsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewAllAssignmentsCommandParserTest.java
Labels: priority.High

#151 Branch ug examples
  docs/UserGuide.md
Labels: type.Documentation

#146 Update UG to include session management
  docs/UserGuide.md
Labels: type.Task, priority.High

#155 Add more assignments and update UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/assignment/initialise/AssignmentMaxGradeInitialise.java
  src/main/java/seedu/address/model/person/assignment/initialise/AssignmentNameInitialise.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonConsultationListStorageTest/invalidDateConsultationListBook.json
  src/test/data/JsonConsultationListStorageTest/invalidTimeConsultationListBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableConsultationListTest/duplicateConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/invalidConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/data/JsonSerializableSessionListTest/duplicateSessionList.json
  src/test/data/JsonSerializableSessionListTest/typicalSessionList.json
  src/test/data/JsonSessionListStorageTest/invalidAndValidSessionList.json
Labels: type.Task, priority.High

#153 Update message and UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.High

#158 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, type.Documentation

#160 Update Task Section for UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/task/DateContainsKeywordsPredicate.java
Labels: type.Documentation

#162 Update annotated ug images
  docs/UserGuide.md
  docs/images/AssignmentCardAnnotated.png
  docs/images/ConsultationCardAnnotated.png
  docs/images/SessionCardAnnotated.png
  docs/images/StudentCardAnnotated.png
  docs/images/TaskCardAnnotated.png
  docs/images/newUiWithAnnotations.png
Labels: type.Documentation

#214 Fix bugs in the User Guide
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#219 Branch userguide encountering errors
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Documentation

#215 Change error message for add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug

#220 Fix Bugs in PE-D
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Medium, type.Documentation

#211 Fix createsession message bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/ui/SessionCard.java
Labels: type.Bug, severity.Low, type.Documentation

#212 Fix takeattendance bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/commands/TakeAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UpdateSessionRemarkCommand.java
  src/main/java/seedu/address/model/session/SessionList.java
  src/test/java/seedu/address/logic/commands/DeleteSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/TakeAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateSessionRemarkCommandTest.java
  src/test/java/seedu/address/model/session/SessionListTest.java
Labels: type.Bug, severity.Medium

#213 Fix viewattendance command and parser bugs
  docs/UserGuide.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/ViewAttendanceCommandParser.java
  src/main/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/session/SessionStudentsContainsStudentsPredicate.java
  src/test/java/seedu/address/logic/commands/CreateSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewAttendanceCommandParserTest.java
  src/test/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/session/SessionStudentsContainsStudentsPredicateTest.java
Labels: type.Bug, severity.Medium

#222 Fix assignment list not appearing
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High

#229 Update edit to save assignment details
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditGradedTestCommand.java
Labels: type.Task, priority.High

#226 Update UG output for add
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditGradedTestCommand.java
  src/main/java/seedu/address/logic/parser/EditGradedTestCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.Medium, type.Documentation

#236 Update PPP
  docs/team/raydenlim.md
Labels: type.Task, priority.High

#231 Update PPP
  docs/AboutUs.md
  docs/team/ldinghan.md
Labels: type.Documentation

#234 Update UG and Message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditGradedTestCommand.java
  src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, type.Documentation

#239 Update table format
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: priority.High, severity.High, type.Documentation

#241 Update br
  docs/UserGuide.md
Labels: type.Documentation

#243 Change UG text color
  docs/stylesheets/main.css
Labels: priority.High, severity.High

#230 Fix PED bug for Consultation and Sessions
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddToConsultCommand.java
  src/main/java/seedu/address/logic/commands/CreateConsultCommand.java
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFromConsultCommand.java
  src/main/java/seedu/address/logic/commands/TabCommand.java
  src/main/java/seedu/address/logic/commands/TakeAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UpdateSessionRemarkCommand.java
  src/main/java/seedu/address/model/ConsultationListBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SessionListBook.java
  src/main/java/seedu/address/model/attendance/Attendance.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/main/java/seedu/address/model/consultation/ConsultationList.java
  src/main/java/seedu/address/model/person/StudentSet.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/session/SessionStudentsTest.java
  src/test/java/seedu/address/model/session/StudentSetPredicateTest.java
  src/test/java/seedu/address/model/session/StudentSetTest.java
  src/test/java/seedu/address/testutil/ConsultationBuilder.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.Medium

#246 Fix assignment commands to show assignments
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommentCommand.java
  src/main/java/seedu/address/logic/commands/EditGradeCommand.java
  src/main/java/seedu/address/logic/commands/ViewAssignmentsCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.Medium

#254 Update Ryan PPP and DG assignments
  docs/DeveloperGuide.md
  docs/diagrams/AssignmentClass.puml
  docs/diagrams/CommentClass.puml
  docs/diagrams/GradeClass.puml
  docs/team/originalidk.md
Labels: priority.High, type.Documentation

#255 Update wesho1107 PPP
  docs/AboutUs.md
  docs/team/wesho1107.md
Labels: type.Documentation

#253 Update PPP
  docs/team/ldinghan.md
Labels: type.Documentation

#251 UG new looks
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: priority.Medium, type.Documentation

#258 Update UG
  docs/UserGuide.md
  docs/images/AssignmentCardAnnotated.png
  docs/images/AssignmentsAnnotated.png
  docs/images/ConsultationCardAnnotated.png
  docs/images/SessionCardAnnotated.png
  docs/images/StudentCardAnnotated.png
  docs/images/TaskCardAnnotated.png
  docs/images/Ui.png
  docs/images/UiWithAnnotations.png
  docs/images/newUiWithAnnotations.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddToConsultCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFromConsultCommand.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/test/java/seedu/address/logic/commands/AddToConsultCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveFromConsultCommandTest.java
Labels: type.Bug, priority.High, type.Documentation

#256 Update UG
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: type.Documentation

#263 Fix color code
  docs/stylesheets/main.css
Labels: priority.High, type.Documentation

#264 Update UG style
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: priority.Medium, type.Documentation

#270 Update table styling in the UG
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: type.Documentation

#269 Branch update ug
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: priority.High, type.Documentation

#252 Update Developer Guide by adding Edit and Delete commands
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/DeleteStudentActivityDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/EditStudentSequenceDiagram.puml
  docs/diagrams/GradedTestClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SessionClassUML.puml
  docs/diagrams/TaskClassUML.puml
  docs/diagrams/UpdateTaskProgressSequenceDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/CommentClass.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteStudentActivityDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/EditStudentSequenceDiagram.png
  docs/images/GradeClass.png
  docs/images/GradedTest.png
  docs/images/SessionClassUML.png
  docs/images/TaskClassUML.png
  docs/images/UpdateTaskProgressSequenceDiagram.png
Labels: type.Documentation

#271 Update PPP
  docs/team/respirayson.md
Labels: type.Documentation

#277 Fix UG typos
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: type.Documentation

#291 Update wesho1107 PPP
  docs/team/wesho1107.md
Labels: priority.Medium, type.Documentation

#290 Update UG for parallel languages
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#298 Add populated Ui image
  docs/images/Ui.png
Labels: priority.Medium, type.Documentation

#299 Update UG enums to uppercase
  docs/UserGuide.md
Labels: type.Documentation

#292 Update session dg
  docs/DeveloperGuide.md
  docs/diagrams/CreateSessionActivityDiagram.puml
  docs/diagrams/SessionClassUML.puml
  docs/diagrams/TakeAttendanceSequenceDiagram.puml
  docs/images/CreateSessionActivityDiagram.png
  docs/images/SessionClassUML.png
  docs/images/TakeAttendanceSequenceDiagram.png
Labels: type.Documentation

#296 Standardize UG with Code
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High, type.Documentation

#300 UG add Known Issues and FAQ
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#304 Change background color for known issues
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#287 Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/AddToConsultSequenceDiagram.puml
  docs/diagrams/ConsultationClassDiagram.puml
  docs/diagrams/CreateConsultSequenceDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/SessionClassUML.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UpdateTaskProgressSequenceDiagram.puml
  docs/images/AddToConsultSequenceDiagram.png
  docs/images/CreateConsultSequenceDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/UpdateTaskProgressSequenceDiagram.png
  src/main/java/seedu/address/model/person/StudentSet.java
  src/main/java/seedu/address/ui/GraphicalResultDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Documentation

#302 Update use cases for Consultation features
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#286 Add UML diagram for assignments
  docs/UserGuide.md
  docs/diagrams/AssignmentClass.puml
  docs/images/AssignmentClass.png
  docs/team/originalidk.md
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommentCommand.java
  src/main/java/seedu/address/logic/commands/ViewAssignmentsCommand.java
Labels: type.Task, priority.High

#308 Update user story and use cases
  docs/DeveloperGuide.md
Labels: type.Documentation

#312 Fix bug as task name regex accepting non alphanumeric
  src/main/java/seedu/address/model/task/TaskName.java
Labels: type.Bug

#274 Update PPP and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CreateEditedGradedTestPersonAD.puml
  docs/diagrams/EditGradedTestSequenceDiagram.puml
  docs/images/CreateEditedGradedTestPersonAD.png
  docs/images/EditGradedTestSequenceDiagram.png
  docs/team/raydenlim.md
Labels: type.Documentation

#320 Update DG Appendix
  docs/DeveloperGuide.md
  docs/team/originalidk.md
Labels: priority.High, type.Documentation

#325 Update DG glossary
  docs/DeveloperGuide.md
Labels: type.Documentation

#326 Update PPP for wesho1107.md
  docs/team/wesho1107.md
Labels: type.Documentation

#323 Use cases for Tasks Management
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#319 Update DG appendix for consultations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RemoveFromConsultActivityDiagram.puml
  docs/images/ConsultationClassDiagram.png
  docs/images/ConsultationClassUMLDiagram.png
  docs/images/RemoveFromConsultActivityDiagram.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, type.Documentation

#329 Fix spacing for PPP
  docs/team/wesho1107.md
Labels: type.Documentation

#328 Update Ryan PPP
  docs/team/originalidk.md
Labels: priority.High, type.Documentation

#330 Redo updating PPP
  docs/team/wesho1107.md
Labels: type.Documentation

#332 Update PPP contributions
  docs/team/originalidk.md
Labels: priority.High, type.Documentation

#316 Fix takeattendance multiple name bug
  src/main/java/seedu/address/logic/parser/TakeAttendanceCommandParser.java
Labels: type.Bug, severity.Medium

#327 Branch DG usecases
  docs/DeveloperGuide.md
  docs/diagrams/EditGradedTestSequenceDiagram.puml
  docs/images/EditGradedTestSequenceDiagram.png
Labels: priority.High, severity.High, type.Documentation

#335 Update PPP
  docs/team/ldinghan.md
Labels: type.Documentation

#315 Branch dg appendix
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#338 Fix takeattendance error display
  src/main/java/seedu/address/logic/commands/TakeAttendanceCommand.java
Labels: type.Bug

#340 Add whitespace to ppp
  docs/team/ldinghan.md
Labels: type.Documentation

#341 Update DG Appendix test
  docs/DeveloperGuide.md
Labels: type.Documentation

#342 Dg appendix tests
  docs/DeveloperGuide.md
Labels: type.Documentation

#343 Update UG and APP parameters
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/AddToConsultCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFromConsultCommand.java
  src/main/java/seedu/address/logic/commands/TabCommand.java
  src/main/java/seedu/address/logic/commands/TakeAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskProgressCommand.java
  src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ViewTasksCommand.java
Labels: priority.High, type.Documentation

#345 Fix indents for DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#348 Fix javadocs
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/CreateConsultCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewTasksCommandParser.java
  src/main/java/seedu/address/model/session/SessionStudentsContainsStudentsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Documentation
