Repository AY2324S1-CS2103T-T15-1/tp, pull requests merged in 2023-10, with the labels that each got.

#27 Add raydenlim.md, Updated raydenlim.md
  4
  docs/AboutUs.md
  docs/images/fakejarvis.png
  docs/images/raydenlim.png
  docs/team/raydenlim.md
Labels: type.Task

#34 Add Jia Cheng info
  docs/AboutUs.md
  docs/images/wesho1107.png
  docs/team/respirayson.md
  docs/team/wesho1107.md
Labels: type.Task

#36 Add Ryan info
  docs/AboutUs.md
  docs/images/originalidk.png
  docs/team/originalidk.md
Labels: type.Task

#31 Branch rayson docs
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#38 Add Ding Han info
  docs/AboutUs.md
  docs/images/ldinghan.png
  docs/team/ldinghan.md
Labels: type.Task

#41 Update UG for consult features
  docs/UserGuide.md
Labels: type.Task, priority.High

#42 Update UserGuide and DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#48 Branch ugdg update
  4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/fakejarvispageopen.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Story, priority.High

#52 Update grading and comment command
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#59 Branch task functionality
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/IncompleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/IncompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskListTest/duplicateTaskList.json
  src/test/data/JsonSerializableTaskListTest/invalidTaskList.json
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CompleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/IncompleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CompleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IncompleteTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#56 Branch assignment feature
  LICENSE
  docs/UserGuide.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AssignmentMapBook.java
  src/main/java/seedu/address/model/ReadOnlyAssignmentMap.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/assignment/Assignment.java
  src/main/java/seedu/address/model/person/assignment/AssignmentMap.java
  src/main/java/seedu/address/model/person/assignment/AssignmentName.java
  src/main/java/seedu/address/model/person/assignment/Grade.java
  src/main/java/seedu/address/model/person/assignment/initialise/AssignmentInitialise.java
  src/main/java/seedu/address/model/person/assignment/initialise/AssignmentMaxGradeInitialise.java
  src/main/java/seedu/address/model/person/assignment/initialise/AssignmentNameInitialise.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAssignmentMap.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonConsultationListStorageTest/invalidDateConsultationListBook.json
  src/test/data/JsonConsultationListStorageTest/invalidTimeConsultationListBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableConsultationListTest/duplicateConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/invalidConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/data/JsonSerializableSessionListTest/duplicateSessionList.json
  src/test/data/JsonSerializableSessionListTest/typicalSessionList.json
  src/test/data/JsonSessionListStorageTest/invalidAndValidSessionList.json
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/assignment/AssignmentMapTest.java
  src/test/java/seedu/address/model/person/assignment/AssignmentNameTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High

#79 Branch dg task
  docs/DeveloperGuide.md
  docs/diagrams/CommandsParserSequenceDiagram.puml
  docs/images/CommandParserSequenceDiagram.png
  docs/images/TaskClass UML.png
  docs/index.md
Labels: type.Task, priority.High

#65 Enhancement of fields for Tasks
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/IncompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskProgressCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/IncompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateTaskProgressCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskProgress.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskListTest/duplicateTaskList.json
  src/test/data/JsonSerializableTaskListTest/invalidTaskList.json
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CompleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/IncompleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskProgressCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CompleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IncompleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UpdateTaskProgressCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditProgressDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement, type.Task, priority.High

#77 Consultation Feature: Delete
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteConsultationCommandParser.java
  src/main/java/seedu/address/model/ConsultationListBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteConsultationCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteConsultationCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, priority.High

#86 Update User Guide initial sections and task
  build.gradle
  docs/UserGuide.md
  docs/images/UiWithAnnotations.png
Labels: type.Task, priority.Medium

#81 Enhancement of Commands for Tasks
  build.gradle
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UpdateTaskProgressCommand.java
  src/main/java/seedu/address/logic/commands/ViewTasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewTasksCommandParser.java
  src/main/java/seedu/address/model/task/DateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskDescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskPriorityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskProgressContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/logic/commands/EditProgressDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ViewTasksCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewTasksCommandParserTest.java
  src/test/java/seedu/address/model/task/DateContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskPriorityContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskProgressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
  src/test/java/seedu/address/testutil/EditProgressDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task, priority.High

#83 Consultation Features: Edit (AddToConsult)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ConsultationClassDiagram.puml
  docs/images/ConsultationClassUMLDiagram.png
  src/main/java/seedu/address/logic/commands/AddToConsultCommand.java
  src/main/java/seedu/address/logic/parser/AddToConsultCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ConsultationListBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/main/java/seedu/address/model/consultation/ConsultationList.java
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/java/seedu/address/logic/commands/AddToConsultCommandTest.java
  src/test/java/seedu/address/logic/commands/AddToConsultationDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddToConsultCommandParserTest.java
  src/test/java/seedu/address/model/consultation/ConsultationListTest.java
  src/test/java/seedu/address/testutil/AddToConsultationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalConsultations.java
Labels: type.Enhancement, priority.High

#88 Add Session Class UML
  docs/DeveloperGuide.md
  docs/diagrams/SessionClassUML.puml
  docs/images/SessionClassUML.png
  docs/index.md
Labels: type.Task, priority.High

#82 Branch add graded test
  docs/team/raydenlim.md
  docs/team/respirayson.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditGradedTestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditGradedTestCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/gradedtest/GradedTest.java
  src/main/java/seedu/address/model/gradedtest/MidTerms.java
  src/main/java/seedu/address/model/gradedtest/PracticalExam.java
  src/main/java/seedu/address/model/gradedtest/ReadingAssessment1.java
  src/main/java/seedu/address/model/gradedtest/ReadingAssessment2.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGradedTest.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/fakejarvis.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonGradedTestListStorageTest/invalidGradedTestList.json
  src/test/data/JsonSerializableGradedTestListTest/duplicateGradedTestList.json
  src/test/data/JsonSerializableGradedTestListTest/invalidGradedTestList.json
  src/test/data/JsonSerializableGradedTestListTest/typicalGradedTestList.json
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditGradedTestCommandTest.java
  src/test/java/seedu/address/logic/parser/EditGradedTestCommandParserTest.java
  src/test/java/seedu/address/model/GradedTestListBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/gradedtest/GradedTestListTest.java
  src/test/java/seedu/address/model/gradedtest/GradedTestNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/gradedtest/ReadingAssessment1Test.java
  src/test/java/seedu/address/model/gradedtest/ReadingAssessment2Test.java
  src/test/java/seedu/address/model/gradedtest/ReadingAssessmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGradedTestTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/GradedTestBuilder.java
Labels: type.Task, type.Bug, priority.High, severity.High

#87 Update DG with grade and comment
  docs/DeveloperGuide.md
  docs/diagrams/CommentClass.puml
  docs/diagrams/GradeClass.puml
  docs/images/CommentClass UML.png
  docs/images/GradeClass UML.png
Labels: type.Task, priority.High

#90 Update DG Add GradedTestClassDiagram
  docs/DeveloperGuide.md
  docs/diagrams/GradedTestClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/GradedTest UML.png
Labels: type.Enhancement, type.Task, priority.High

#91 Update UG and DG
  docs/DeveloperGuide.md
  docs/team/originalidk.md
  docs/team/wesho1107.md
Labels: priority.High

#78 Branch session remarks
  build.gradle
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/UpdateSessionRemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateSessionRemarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionRemark.java
  src/main/java/seedu/address/model/session/exceptions/DuplicateSessionException.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/resources/view/SessionListCard.fxml
  src/test/data/JsonSerializableSessionListTest/duplicateSessionList.json
  src/test/data/JsonSerializableSessionListTest/typicalSessionList.json
  src/test/java/seedu/address/logic/commands/CreateSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateSessionRemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UpdateSessionRemarkCommandParserTest.java
  src/test/java/seedu/address/model/session/SessionRemarkTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSessionTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalSessions.java
Labels: type.Enhancement, type.Task, priority.High

#96 Enhance viewattendance functionality
  src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/ViewAttendanceCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewAttendanceCommandParserTest.java
Labels: type.Enhancement, type.Bug, priority.Medium

#99 Add TOC to UG Add yml file
  docs/UserGuide.md
  docs/_config.yml
  docs/team/raydenlim.md
Labels: type.Enhancement, priority.Medium

#103 Fix error messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High

#104 Convert address to telegram handle
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditCommentCommand.java
  src/main/java/seedu/address/logic/commands/EditGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditGradedTestCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableConsultationListTest/duplicateConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/data/JsonSerializableSessionListTest/duplicateSessionList.json
  src/test/data/JsonSerializableSessionListTest/typicalSessionList.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/assignment/TelegramHandleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task, priority.Medium

#109 Add logo to Ui
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/emaillogo.png
  src/main/resources/images/phonelogo.png
  src/main/resources/images/telelogo.png
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, type.Task, priority.Medium

#93 Add Assignment List UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewAllAssignmentsCommand.java
  src/main/java/seedu/address/logic/commands/ViewAssignmentsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewAllAssignmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewAssignmentsCommandParser.java
  src/main/java/seedu/address/model/person/assignment/initialise/AssignmentNameInitialise.java
  src/main/java/seedu/address/ui/AssignmentCard.java
  src/main/java/seedu/address/ui/AssignmentListPanel.java
  src/main/java/seedu/address/ui/AssignmentNameCard.java
  src/main/java/seedu/address/ui/AssignmentNameListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AssignmentListCard.fxml
  src/main/resources/view/AssignmentListPanel.fxml
  src/main/resources/view/AssignmentNameListCard.fxml
  src/main/resources/view/AssignmentNameListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAllAssignmentsCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAssignmentsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewAllAssignmentsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewAssignmentsCommandParserTest.java
Labels: type.Task, priority.High

#112 Add individual assignment list person index
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#113 Fix Session String
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Bug, priority.Medium, severity.Medium

#101 Branch ugdg update
  docs/UserGuide.md
  docs/_config.yml
  docs/_markbind/layouts/default.md
  docs/stylesheets/main.css
  src/main/java/seedu/address/model/GradedTestListBook.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Enhancement, type.Task, priority.High

#106 Add testcases for email
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Task, priority.High

#111 Consultation Feature: Edit (RemoveFromConsult)
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddToConsultCommand.java
  src/main/java/seedu/address/logic/commands/CreateConsultCommand.java
  src/main/java/seedu/address/logic/commands/RemoveFromConsultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveFromConsultCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/consultation/exceptions/PersonNotFoundInConsultException.java
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/java/seedu/address/logic/commands/AddToConsultCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateConsultationCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveFromConsultCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveFromConsultationDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveFromConsultCommandParserTest.java
  src/test/java/seedu/address/testutil/RemoveFromConsultationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalConsultations.java
Labels: type.Task, priority.High

#115 Email: change valid domain to u.nus.edu.sg
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonConsultationListStorageTest/invalidDateConsultationListBook.json
  src/test/data/JsonConsultationListStorageTest/invalidTimeConsultationListBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAssignmentMapTest/invalidAssignmentMap.json
  src/test/data/JsonSerializableConsultationListTest/duplicateConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/invalidConsultationList.json
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/data/JsonSerializableSessionListTest/duplicateSessionList.json
  src/test/data/JsonSerializableSessionListTest/typicalSessionList.json
  src/test/data/JsonSessionListStorageTest/invalidAndValidSessionList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Bug, priority.High

#107 DG and UG Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/CommandsParserSequenceDiagram.puml
  docs/diagrams/TaskClassUML.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/TaskClass UML.png
  docs/images/TaskClassUML.png
  docs/team/ldinghan.md
  docs/team/wesho1107.md
Labels: type.Task, priority.High

#124 Update webtitle suffix
  docs/site.json
Labels: type.Bug, priority.Medium

#126 Add delete session command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteSessionCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteSessionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Enhancement, type.Task, priority.Medium

#114 Fix messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/gradedtest/GradedTest.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableConsultationListTest/typicalConsultationList.json
  src/test/data/JsonSerializableGradedTestListTest/typicalGradedTestList.json
  src/test/data/JsonSerializableSessionListTest/typicalSessionList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/gradedtest/GradedTestTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/storage/JsonGradedTestListStorageTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalGradedTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High
